# Source: jxboot-helmfile-resources/templates/tekton-git-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: tekton-git
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: password
      key: secret/data/jx/pipelineUser
      property: token
    - name: username
      key: secret/data/jx/pipelineUser
      property: username
  template:
    metadata:
      annotations:
        tekton.dev/git-0: "https://github.com"
        meta.helm.sh/release-name: 'jxboot-helmfile-resources'
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: tekton-pipelines
    type: kubernetes.io/basic-auth
