# Source: oauth2-proxy/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  labels:
    app: oauth2-proxy
    chart: oauth2-proxy-5.0.3
    heritage: Helm
    release: oauth2-proxy
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: oauth2-proxy
  namespace: jx
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"oauth2-proxy","properties":[{"name":"cookie-secret","question":"the cookie secret","help":"the cookie secret","generator":"password","minLength":32,"maxLength":32},{"name":"client-id","question":"the client id","help":"client id"},{"name":"client-secret","question":"the client secret","help":"client secret"}],"mandatory":true}'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: cookie-secret
      key: secret/data/oauth2/proxy
      property: cookie-secret
    - name: client-secret
      key: secret/data/oauth2/proxy
      property: client-secret
    - name: client-id
      key: secret/data/oauth2/proxy
      property: client-id
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'oauth2-proxy'
        secret.jenkins-x.io/schema-object: '{"name":"oauth2-proxy","properties":[{"name":"cookie-secret","question":"the cookie secret","help":"the cookie secret","generator":"password","minLength":32,"maxLength":32},{"name":"client-id","question":"the client id","help":"client id"},{"name":"client-secret","question":"the client secret","help":"client secret"}],"mandatory":true}'
      labels:
        app: oauth2-proxy
        chart: oauth2-proxy-5.0.3
        heritage: Helm
        release: oauth2-proxy
    type: Opaque
