# Source: addons/templates/secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secret
  namespace: identity
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: admin-password
      key: secret/data/keycloak/secret
      property: admin-password
    - name: management-password
      key: secret/data/keycloak/secret
      property: management-password
    - name: tls-keystore-password
      key: secret/data/keycloak/secret
      property: tls-keystore-password
    - name: tls-truestore-password
      key: secret/data/keycloak/secret
      property: tls-truestore-password
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'addons-identity'
    type: Opaque
