# Source: addons/templates/secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-postgresql-secret
  namespace: identity
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: postgresql-password
      key: secret/data/keycloak/postgresql/secret
      property: postgresql-password
    - name: postgresql-postgres-password
      key: secret/data/keycloak/postgresql/secret
      property: postgresql-postgres-password
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'addons-identity'
    type: Opaque
