# Source: addons/templates/secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secret
  namespace: identity
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: admin-password
      key: secret/data/keycloak/secret
      property: admin-password
    - name: management-password
      key: secret/data/keycloak/secret
      property: management-password
    - name: password
      key: secret/data/keycloak/secret
      property: password
    - name: tls-keystore-password
      key: secret/data/keycloak/secret
      property: tls-keystore-password
    - name: tls-truestore-password
      key: secret/data/keycloak/secret
      property: tls-truestore-password
  template:
    metadata:
      annotations:
        secret.jenkins-x.io/schema-object: '{"properties":[{"question":"the Admin password for Keycloak","minLength":8,"maxLength":20,"name":"admin-password","generator":"password"},{"question":"the Management password for Keycloak","minLength":8,"maxLength":20,"name":"management-password","generator":"password"},{"question":"the DB password for Keycloak","minLength":8,"maxLength":20,"name":"password","generator":"password"}{"question":"the Tsl keystore Password for Keycloak","minLength":12,"maxLength":45,"name":"tls-keystore-password","generator":"password"},{"question":"the Tsl truestore Password for Keycloak","minLength":12,"maxLength":45,"name":"tls-truestore-password","generator":"password"}],"mandatory":"true","name":"keycloak-secret"}'
        meta.helm.sh/release-name: 'addons-identity'
    type: Opaque
