filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: identity
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
releases:
- chart: bitnami/keycloak
  name: keycloak
  values:
  - values.yaml
  - ../../versionStream/charts/bitnami/keycloak/values.yaml.gotmpl
  - jx-values.yaml
- chart: ../../charts/addons-identity
  name: addons-identity
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
