filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: identity
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
releases:
- chart: bitnami/keycloak
  name: keycloak
  values:
  - values.yaml
templates: {}
renderedvalues: {}
