apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-ihsws-it-p
  namespace: jx
spec:
  secretName: tls-ihsws-it-p
  issuerRef:
    name: letsencrypt-dns01-prod
    kind: ClusterIssuer
  dnsNames:
  - '*.ihsws.it'
