# Source: addons/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: clouddns-dns01-solver-svc-acct
  namespace: cert-manager
  annotations:
    meta.helm.sh/release-name: 'addons-cert-manager'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
type: Opaque
data: {}
