filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: cert-manager
repositories:
- name: jetstack
  url: https://charts.jetstack.io
releases:
- chart: jetstack/cert-manager
  name: cert-manager
  values:
  - values.yaml
- chart: ../../charts/addons-cert-manager
  name: addons-cert-manager
templates: {}
renderedvalues: {}
