filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: nfs-subdir-ext-prov
repositories:
- name: nfs-subdir-external-provisioner
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
releases:
- chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
  name: nfs-subdir-external-provisioner-w
  values:
  - values-w.yaml
  - jx-values.yaml
- chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
  name: nfs-subdir-external-provisioner-l
  values:
  - values-l.yaml
  - jx-values.yaml
templates: {}
renderedvalues: {}
