apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  annotations:
    secret.jenkins-x.io/schema-object: '{"properties":[{"question":"the Admin password for Keycloak","minLength":8,"maxLength":20,"name":"admin-password","generator":"password"},{"question":"the Management password for Keycloak","minLength":8,"maxLength":20,"name":"management-password","generator":"password"},{"question":"the Tsl keystore Password for Keycloak","minLength":12,"maxLength":45,"name":"tls-keystore-password","generator":"password"},{"question":"the Tsl truestore Password for Keycloak","minLength":12,"maxLength":45,"name":"tls-truestore-password","generator":"password"}],"mandatory":"true","name":"keycloak-secret"}'
type: Opaque
data:
  admin-password: 
  management-password: 
  tls-keystore-password: 
  tls-truestore-password: 
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgresql-secret
type: Opaque
data:
  postgresql-password: 
  postgresql-postgres-password: 
