apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  admin-password: Y2hhbmdlLW1lMTIz
  management-password: Y2hhbmdlLW1lMTIz
  tls-keystore-password: Y2hhbmdlLW1lMTIz
  tls-truestore-password: Y2hhbmdlLW1lMTIz
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgresql-secret
type: Opaque
data:
  postgresql-password: Y2hhbmdlLW1lMTIz
  postgresql-postgres-password: Y2hhbmdlLW1lMTIz
