apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  admin-password: 
  management-password: 
  tls-keystore-password: 
  tls-truestore-password: 
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgresql-secret
type: Opaque
data:
  postgresql-password: 
  postgresql-postgres-password: 
