# Source: nfs-subdir-external-provisioner/templates/role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    chart: nfs-subdir-external-provisioner-4.0.16
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: nfs-subdir-external-provisioner
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: leader-locking-nfs-subdir-external-provisioner
  annotations:
    meta.helm.sh/release-name: 'nfs-subdir-external-provisioner'
  namespace: nfs-subdir-ext-prov
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
