# Source: jxboot-helmfile-resources/templates/tekton-container-registry-auth-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: tekton-container-registry-auth
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    secret.jenkins-x.io/replica-source: "true"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx-production
  annotations:
    secret.jenkins-x.io/replica: 'true'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: .dockerconfigjson
      key: secret/data/tekton/container/registry/auth
      property: .dockerconfigjson
  template:
    metadata:
      annotations:
        tekton.dev/docker-0: "https://index.docker.io/v1/"
        meta.helm.sh/release-name: 'jxboot-helmfile-resources'
      labels:
        app.kubernetes.io/component: webhook
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: tekton-pipelines
        secret.jenkins-x.io/replica-source: "true"
    type: kubernetes.io/dockerconfigjson
