# Source: nfs-subdir-external-provisioner/templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    chart: nfs-subdir-external-provisioner-4.0.16
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: nfs-subdir-external-provisioner-w
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: nfs-client-w
  annotations:
    meta.helm.sh/release-name: 'nfs-subdir-external-provisioner-w'
  namespace: nfs-subdir-ext-prov
provisioner: cluster.local/nfs-subdir-external-provisioner-w
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  archiveOnDelete: "true"
mountOptions:
  - rw
  - nolock
  - noatime
  - tcp
