apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: identity
type: Opaque
data: {}
#  admin-password: bzRHYjJaN2d5Y2pWWmI=
#  management-password: R2EzOFNvTnpMOURTZHk=
#  tls-keystore-password: ejJEbm9SUXpBUmszZTQ=
#  tls-truestore-password: QW1YczdiU1g1ZFpIcnE=