apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  admin-password: bzRHYjJaN2d5Y2pWWmI=
  management-password: R2EzOFNvTnpMOURTZHk=
  tls-keystore-password: ejJEbm9SUXpBUmszZTQ=
  tls-truestore-password: QW1YczdiU1g1ZFpIcnE=
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgresql-secret
type: Opaque
data:
  postgresql-password: RjY1UWtXSkw3dVNMV20=
  postgresql-postgres-password: NEpMbXRtcDJMeUZ2elM=
