# Source: keycloak/charts/postgresql/templates/secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-postgresql
  namespace: identity
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-11.1.14
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: postgres-password
      key: secret/data/keycloak/postgresql
      property: postgres-password
    - name: password
      key: secret/data/keycloak/postgresql
      property: password
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'keycloak'
      labels:
        app.kubernetes.io/name: postgresql
        helm.sh/chart: postgresql-11.1.14
        app.kubernetes.io/instance: keycloak
        app.kubernetes.io/managed-by: Helm
    type: Opaque
